[project]
name = "annealedrl"
version = "0.1.0"
description = "annealed RL experiments"
readme = "README.md"
requires-python = "==3.11.13"

dependencies = [
    "einops>=0.8.1",
    "gcsfs>=2024.6.0",
    "hydra-core==1.3.2",
    "jax==0.8.0; platform_system != 'Linux'",
    "jax[tpu]==0.8.0; platform_system == 'Linux'",
    "jaxtyping>=0.3.4",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.10",
    "stax",
    "torch>=2.9.0",
    "transformers>=4.57.3",
    "datasets>=4.5.0",
    "openai>=2.21.0",
    "tensorboard==2.20.0",
    "tensorboard-plugin-profile==2.21.6",
    "pylatexenc>=2.10",
    "openbench>=0.5.3",
    "optax==0.2.7",
    "wandb==0.25.0",
    "rich<14.0.0",
    "epath>=0.7",
]

[project.optional-dependencies]
data = [
    "datasets>=4.4.2",
    "gcsfs>=2025.3.0",
    "matplotlib>=3.10.8",
    "notebook>=7.5.3",
    "opencv-python>=4.12.0.88",
    "orbax-checkpoint>=0.11.31",
    "tfds-nightly>=4.9.9.dev202510250044",
]

eval = [
    "vllm-tpu==0.12.0; platform_system == 'Linux'",
    "lm-eval>=0.4.11",
]


[tool.uv.sources]
stax = { git = "https://github.com/adityamakkar000/stax.git", branch="aditya/addName"}
