defaults:
  - base 
  - data_config: debug
  - model_config: qwen_0.6b
  - sharding_config: fsdp
  - loss_config: loss
  - override loss_config/inference_config: debug
  - _self_

grad_accum_steps: 1
seed: 0
num_steps: 250
val_steps: 1
val_interval: 50

optimizer: "adamw"
weight_decay: 0.01
grad_clip: 1.0

learning_rate_init: 1e-6
learning_rate_peak: 1e-6
learning_rate_end: 1e-6
warmup_steps: 0.0
decay_steps: 1.0

spot_training: true 
checkpoint_interval: 50
best_metric: null
max_checkpoints_to_keep: 1

wandb_config: 
  project: "Debug"
  notes: null
  tags: null

data_config:
  train_config:
    batch_size: 1024
  val_config:
    batch_size: 1024
loss_config:
  inference_config:
    max_seq_len: 2048
    _max_decode_prompts: 32
    _max_decode_batch_size: 128
    n_replicas: 4
    group_size: 8
    temperature: 1.0
    reasoning_budget: null
    think_mode: true
    system_prompt: true
  rl_config:
    ppo_minibatch_size: 64

metrics_to_log:
  - "train/loss"
  - "train/is_ratio_step_0"
  - "train/mean_reward"
  - "val/mean_reward"
  - "train/num_unparsable"