defaults:
  - base 
  # - model_config: qwen_0.6b_base
  - sharding_config: fsdp
  - loss_config: loss
  - datasets@data_config: gsm8k
  - override loss_config/inference_config: debug
  - _self_

model_config:
  model_args:
    _target_: src.model.llama.Llama3
    vocab_size: 128256
    sequence_len: 16384
    model_dim: 4096
    d_ff: 14336
    n_heads: 32
    n_kv_heads: 8
    n_layers: 32
    rope_base: 500000
    activation_dtype: "bfloat16"
  hf_model_name: "meta-llama/Llama-3.1-8B"

data_config:
  batch_size: 512

grad_accum_steps: 4
seed: 0
num_steps: 250

optimizer: "adamw"
weight_decay: 0.01
grad_clip: 1.0

learning_rate_init: 1e-6
learning_rate_peak: 1e-6
learning_rate_end: 1e-6
warmup_steps: 0.0
decay_steps: 1.0

spot_training: true 
checkpoint_interval: 50
max_checkpoints_to_keep: 1

wandb_config: 
  project: "Debug"
  notes: null
  tags: null

loss_config:
  inference_config:
    max_seq_len: 512
    _max_decode_prompts: 8
    _max_decode_batch_size: 64
    n_replicas: 4
    group_size: 16
    temperature: 1.0
    reasoning_budget: null 
    think_mode: true
    system_prompt: false

async_config:
  train_workers: 1
  max_lag: 2

metrics_to_log:
  - "train/loss"
  - "train/is_ratio_step_0"
  - "train/mean_reward"
  - "val/mean_reward"
  - "train/num_unparsable"