defaults:
  - base 
  - model_config: qwen_0.6b_base
  - loss_config: loss
  - datasets@data_config: gsm8k
  - override loss_config/inference_config: debug
  - _self_

data_config:
  batch_size: 512

grad_accum_steps: 4
seed: 0
num_steps: 250

optimizer: "adamw"
weight_decay: 0.01
grad_clip: 1.0

learning_rate_init: 1e-6
learning_rate_peak: 1e-6
learning_rate_end: 1e-6
warmup_steps: 0.0
decay_steps: 1.0

spot_training: true 
checkpoint_interval: 50
max_checkpoints_to_keep: 1

wandb_config: 
  project: "Debug"
  notes: null
  tags: null

loss_config:
  inference_config:
    max_seq_len: 512
    max_decode_prompts: 8
    max_decode_batch_size: 64
    n_replicas: 4
    group_size: 16
    temperature: 1.0
    reasoning_budget: null 
    think_mode: true
    system_prompt: false
  rl_config:
    _target_: src.workers.loss.CISPOLoss
    epsilon: 4

sharding_config: 
  opt_state_offload: false
  data_shard_dim: 0
  min_bytes_for_fsdp: 1048576
  weight_shard_dim: 0
  cp_shard_dim: 1
  dp_group_size: 1
  cp_group_size: 1
  fsdp_group_size: -1


async_config:
  train_workers: 1
  max_lag: 8

metrics_to_log:
  - "train/loss"
  - "train/is_ratio_step_0"
  - "train/mean_reward"
  - "val/mean_reward"
  - "train/num_unparsable"

debug: true