defaults:
  - base 
  - data_config: main
  - model_config: qwen_0.6b
  - sharding_config: fsdp
  - loss_config: loss
  - _self_

grad_accum_steps: 1
seed: 0
num_steps: 1000
val_interval: 100

optimizer: "adamw"
weight_decay: 0.01
grad_clip: 1.0

learning_rate_init: 0.0
learning_rate_peak: 1e-4
learning_rate_end: 1e-5
warmup_steps: 0.1
decay_steps: 0.9

spot_training: true 
checkpoint_interval: 100
best_metric: null
max_checkpoints_to_keep: 5

wandb_config: 
  project: "AnnealedRL"
  notes: null
  tags: null

metrics_to_log:
  - "train/loss"
  - "val/loss"