defaults:
  - base 
  - data_config: run_1
  - model_config: qwen_1.7b
  - sharding_config: fsdp
  - loss_config: loss
  - _self_

grad_accum_steps: 1
val_steps: 1
seed: 0
num_steps: 1000
val_interval: 50

optimizer: "adamw"
weight_decay: 0.01
grad_clip: 1.0

learning_rate_init: 1e-5
learning_rate_peak: 1e-5
learning_rate_end: 1e-5
warmup_steps: 0.1
decay_steps: 0.9

spot_training: true 
checkpoint_interval: 50
best_metric: null
max_checkpoints_to_keep: 5

wandb_config: 
  project: "AnnealedRL"
  notes: null
  tags: null

# prompts = 64 / 8 = 8
data_config:
  train_config:
    batch_size: 512
  val_config:
    batch_size: 512
loss_config:
  inference_config:
    max_seq_len: 16384
    batch_size: 2
    n_replicas: 4
    group_size: 8
    temperature: 1.0
  rl_config:
    algorithm: cispo
    epsilon_high: 0.25
    epsilon_low: 0.18
  grad_steps: 4

metrics_to_log:
  - "train/loss"
  - "train/is_ratio_step_0"
  - "train/mean_reward"
  - "val/mean_reward"