# note that name must be the same as registery function decorator name
defaults:
  - datasets@train_config: omnimath
  - datasets@val_config: omnimath

train_config:
  batch_size: 128

val_config:
  batch_size: 32
