model_args:
  _target_: src.model.llama.Llama3
  vocab_size: 128256
  sequence_len: 16384
  model_dim: 4096
  d_ff: 14336
  n_heads: 32
  n_kv_heads: 8
  head_dim: 128
  n_layers: 32
  rope_base: 500000
  activation_dtype: "bfloat16"
hf_model_name: "meta-llama/Llama-3.1-8B-Instruct"
