qwen_config:
  vocab_size: 151936
  d_ff: 3072
  sequence_len: 10112
  model_dim: 1024
  n_heads: 16
  n_groups: 8
  n_layers: 28
  head_dim: 128
  rope_base: 1000000
  activation_dtype: "bfloat16"
hf_model_name: "Qwen/Qwen3-0.6B"
