defaults:
  - base
  - _self_

tasks:
  - "aime"

vllm_config:
  max_sequences: 128
  max_batched_tokens: 2048
  tensor_parallel_size: 2
  data_parallel_size: 4

model_config:
  model_name: "debug"
  use_best_ckpt: false
  step_number: -1 # take last step 

temperature: 1.0
top_p: 1.0
max_tokens: 8192
epochs: 1
