# short config for debugging 
temperature: 0.6
top_p: 0.95
top_k: null
max_seq_len: 512
intial_sequence_len: 64
max_prefill_sequence_len: 512
batch_size: 2
n_replicas: 4
group_size: 8
kv_cache_dtype: "bfloat16"
precompile: true
reasoning_budget: 256
params_dtype: "float32"
